### ISSUE TITLE
Comments on Sessions

### ISSUE THREAD

**Issue by sharafian** [adrianhopebailie/open-payments#14]
A few small things:

1. The name appears to be a relative URL starting with `//`. Is that intentional or should it be `https://`?

2. The spend example doesn't have an error message for when there is insufficient balance to spend. That would be helpful to define

3. I was thinking of the session balance as being tracked in two separate fields, paid and spent, so that you can have more insight into the details of the session. I'm not strongly opposed to the way balance is tracked in the proposal but I like the idea of two monotonically increasing balances rather than one that goes up and down.

**Comment by wilsonianb** [comment]
For 1, see https://github.com/adrianhopebailie/open-payments/issues/7 and https://aip.dev/122

**Comment by adrianhopebailie** [comment]
> The spend example doesn't have an error message for when there is insufficient balance to spend. That would be helpful to define

Have added that in.

> I was thinking of the session balance as being tracked in two separate fields, paid and spent, so that you can have more insight into the details of the session. I'm not strongly opposed to the way balance is tracked in the proposal but I like the idea of two monotonically increasing balances rather than one that goes up and down.

Have also added this
