### ISSUE TITLE
Make invoices pull payments

### ISSUE THREAD

**Issue by wilsonianb** [adrianhopebailie/open-payments#15]
From https://github.com/adrianhopebailie/open-payments/issues/6
>Lets distinguish between an "invoice" which has a fixed amount, known ahead of time, and a "session account" an ephemeral sub-account that is simply used to track payments during a session.

An "invoice" which has a fixed amount, known ahead of time sounds similar to a mandate. The recipient is wanting to receive X amount from the counterparty.

What if such a payment were represented by both a mandate at the sender's wallet and an invoice at the receiver's wallet?

A receiver initiated payment would involve creating an invoice that includes the counterparty's payment pointer. The wallet would then attempt to create a mandate at the counterparty's wallet to fulfill the invoice.

This changes invoices from being push payments to pull payments.

Could we take it even further and make everything a pull payment?

A sender initiated payment would involve creating a mandate that includes the counterparty's payment pointer. The wallet would then attempt to create an invoice at the counterparty's wallet which includes the mandate URL and access token.

For web monetization, the wm provider would create a subscription-esque mandate based on the amount per second rate that it's willing to pay. (The wm provider would subsequently delete the mandate when the user leaves the site, cutting off the stream.)

Unfortunately that'd bring us back to sending web monetization payments to an invoice instead of a session account.
However, we could introduce [invoice](https://stripe.com/docs/api/invoices) [items](https://stripe.com/docs/api/invoiceitems) as individual charges on an invoice resource. Payment verification would be achieved by creating an invoice item on the invoice and seeing if the invoice balance exceeds all invoice item amounts. It'd be a little weird that (for at least these invoices) the total balance would be allowed to exceed the total of invoice item amounts, but I like how this captures the idea of a website's backend server issuing a micro invoice for serving a request.

**Comment by adrianhopebailie** [comment]
> An "invoice" which has a fixed amount, known ahead of time sounds similar to a mandate. The recipient is wanting to receive X amount from the counterparty.

An invoice and a mandate are quite different.

An invoice, as is typical for any business, is something you create when someone is going to pay you money. i.e. If you owe me money I create and invoice and send it to you and ask you to pay it.

The invoice is created and exists primarily on my system.

A mandate is also well-known concept in payments today (often called a debit mandate). It is an agreement from a payer that that a third-party can pull money from their account.

> What if such a payment were represented by both a mandate at the sender's wallet and an invoice at the receiver's wallet?

It is conceivable that I create an invoice on my system because you owe me money and instead of paying it you create a mandate on your system for the same amount and give me permission to execute it.

> This changes invoices from being push payments to pull payments.

I don't think so. The invoice could still have been fulfilled by the sender just sending the money. (We're planning to model this case with the Rafiki demo wallet soon.) This is often called the "Merchant-Request-To-Pay" case.

So the two are still required and fulfil different purposes.

> Could we take it even further and make everything a pull payment?

I think we should only use pull if we have to. It introduces a lot of complexity that we should avoid if possible. E.g. What if I have a mandate but when I try to pull the funds the account is empty?

> However, we could introduce invoice items as individual charges on an invoice resource.

I did look at that as an option. Each payment in and each spend could be a line item. But, is it necessary to track all of the sessions from a user under a single invoice?

i.e. What's the cardinality of the relationships between sessions and invoices?

If we bucket multiple sessions under an invoice then the question is, what does that invoice represent? Who would create it and under what conditions?

**Comment by wilsonianb** [comment]
Thanks for the counterpoints.

I didn’t mean to equate invoices and mandates, and definitely have your same definitions in mind. I’m mainly wondering if asking for the payer to authorize a mandate could be the standard means of asking them to pay an invoice. Or stated differently: do we need to support both mandates and "Merchant-Request-To-Pay” if the request to pay can just be the receiver wallet attempting to create a mandate at the payer’s wallet (which presumably then asks the user to authorize)?

Invoice + Mandate flow:

1. Receiver creates invoice at wallet
2. Receiver's wallet creates mandate at payer's wallet
3. Payer's wallet asks payer to authorize mandate

Merchant-Request-To-Pay flow:

1. Receiver creates invoice at wallet
2. Receiver sends invoice to payer “out-of-band”
3. Payer initiates payment at own wallet

IMO, it seems more convenient for the payer to not have to log in to their wallet and enter payment details to pay an invoice. Their experience could be as simple as tapping yes or no in a prompt from their wallet.

I realize this would require the recipient to know the payer’s payment pointer (in order for the receiver’s wallet to be able to interact with the payer’s wallet), but perhaps that could be included in the payer’s contact info that the receiver presumably already has in order to send the invoice to the payer.

>I think we should only use pull if we have to. It introduces a lot of complexity that we should avoid if possible. E.g. What if I have a mandate but when I try to pull the funds the account is empty?

It seems like wallets will need retry logic to support mandates to any extent. I _can_ see how the potential mishandling of a mandate’s access token entails risks that don’t exist with push payments. Are there other major cons to pull payments that I’m overlooking?

>But, is it necessary to track all of the sessions from a user under a single invoice?
>i.e. What's the cardinality of the relationships between sessions and invoices?
>If we bucket multiple sessions under an invoice then the question is, what does that invoice represent?

I was actually thinking of our original idea of a single invoice per web monetization id (session). Invoice items would be used to represent individual charges such as individual API requests to a website’s backend (e.g. for X more seconds of video) during a single session. It’s basically just a more conceptually justifiable means of having the receiver wallet track the amount used for an invoice balance.

**Comment by adrianhopebailie** [comment]
The major difference between a mandate and an invoice that the mandate represents **authorisation** and the invoice is a request for **payment**.

The combination of the two and how they are used together will depend on the use case.

In the "Invoice + Mandate flow" you describe above I assume that the intended UX is for the sender to authorise a single payment to the receiver and then the mandate exhausted? In which case, why do you need the mandate at all?

Could the flow be:

- Receiver creates invoice at wallet
- Receiver's wallet submits invoice to payer's wallet
- Payer's wallet asks payer to authorize payment of invoice

**Comment by wilsonianb** [comment]
Good point. It does make sense to not even create the mandate for an immediate one time payment.

For recurring or delayed payments, I was thinking the invoice could have the same start, interval, etc details that are possible in a mandate. Then the receiving wallet can automatically pull with the receiver needing to do anything.

**Comment by wilsonianb** [comment]
>Receiver's wallet submits invoice to payer's wallet

How would the invoice (url?) be submitted (wallet to wallet) in the case of an immediate one time payment like this?
Would it be included in a POST to the mandates endpoint even though a mandate wouldn't be created? In which case, what response is returned if a push payment happens without creating a mandate?
Or would it need to be submitted by some other means?

**Comment by matdehaast** [comment]
I would be hesitate to have an endpoint to submit arbitrary invoices mainly because it opens up potential for abuse.

**Comment by wilsonianb** [comment]
The sender's wallet could make it a paid API call to alleviate that concern.
(And you'd be hard pressed to find two better entities to offer and consume a paid API endpoint than a pair of ILP wallets :smiley: )
