### ISSUE TITLE
Paid API use case

### ISSUE THREAD

**Issue by wilsonianb** [adrianhopebailie/open-payments#16]
With public BTP uplinks, developers were previously able to use ILP STREAM directly in order to send and receive money via Interledger. Payment verification was a natural feature of the setup given the visibility into the STREAM connections.

A particular use case for this was paid API endpoints, in which a web service requires payment before serving HTTP requests:

1. The client (using something like [ilp-fetch](https://github.com/interledgerjs/ilp-fetch)) would send a request
2. The server would return 402 Payment Required (using something like [cog](https://github.com/coilhq/cog)) along with a price and generated `destination_address` and `shared_secret` in the response headers (Note that SPSP isn’t used here)
3. The client would make the payment and resend the request including the STREAM connection tag in the headers
4. The server could verify the amount received in the connection before finally serving the request

Without public ILP access, developers will need either of the following to support paid API endpoints:

- a BTP uplink from their ILP wallet
- payment and payment verification functionality from their ILP wallet, which would handle the actual ILP payments

OPay seems relevant to how the latter can be achieved, which has the added benefit of developers not having to touch ILP directly (no more running moneyd, uplinks, etc).

API services can be paid either directly (a la ilp-fetch) or via web monetization (where a portion of the amount paid is used to cover the request(s) costs). It would be nice if both cases could be handled by the (final) request including a payment-id(?) header with the name of the resource that the receiver should query at their wallet to verify the payment was received.

I’m unclear, however, how the two parties get to that point with a direct payment (no web monetization).
After the client sends the initial request, possible next steps include:

- the server creates an invoice ("Merchant-Request-To-Pay”)
- the server includes their payment pointer or `payment_invoices_endpoint` and price in the 402 response for the client to create an invoice
- the server creates a session
- the server includes their payment pointer or `payment_sessions_endpoint` and price in the 402 response for the client to create a session
- the server creates a mandate at the client wallet (if the initial request included the client’s payment pointer or `payment_mandates_endpoint`)
- the server includes the price in the 402 response and the client creates an authorized mandate
- the server gets a `shared_secret` and `destination_address` (containing a connection tag) from its wallet, which creates an invoice(?) with the tag as the id upon payment. (Not currently included in the OPay spec but was previously discussed in [slack](https://interledger.slack.com/archives/CPL2HTF54/p1572563613180000))

Does it make sense to use invoices here since no service has been rendered yet (the request isn’t served until after payment)?
Does it make sense to use sessions here if it’s potentially a single one-off request and payment?

**Comment by wilsonianb** [comment]
There's also the case of the server specifying a recurring amount for the price. (For example, a codius host would include a rate in the 402 response indicating the price for ongoing hosting of the application the client is wanting to upload.) The server would verify that the first interval is paid before serving the request.

It seems like recurring payments like this would need to involve a mandate.

For recurring (or even one-off pull) payments, what is triggering each pull at the receiver end. Should the receiver repeatedly tell its wallet to pull, or is there some resource on the wallet informing it to pull at the specified interval?

**Comment by adrianhopebailie** [comment]
I think the best way to handle this is with sessions/invoices.

If a client makes an API call and get's back a 402 it could also get a `Location` header that directs it to the invoice/session that can be paid.

If the pricing model is per request (or batch of requests) then the invoice would be for a fixed amount and the client would GET the invoice and thereby have ther STREAM credentials to pay it.

If the pricing is open ended or consumption based then I'd imagine the 402 would provide details of a session to pay into. The client can send money to the session and then also track the balance as it is consumed after making paid API calls.

We don't currently handle dynamic price advertisements with the Web Monetization use case, do you think we need to?
