### ISSUE TITLE
Why headers ?

### ISSUE THREAD

**Issue by sublimator** [adrianhopebailie/open-payments#3]
For ILP packets, why use headers and not the POST body? 
It's not obvious to me and I'm curious

**Comment by adrianhopebailie** [comment]
It seems more correct to me.

We are using HTTP to transmit a request/response pair with headers so we should use the feature of HTTP that is designed for that purpose.

**Comment by sublimator** [comment]
Can you elaborate on that further? I still don't really get it. 
At least in the example, the body is empty. 
Are you imagining the body to be used for something else?

**Comment by adrianhopebailie** [comment]
Have put the idea of alternate ILP packet encoding to the side for now
