### ISSUE TITLE
Invoice id vs URL

### ISSUE THREAD

**Issue by wilsonianb** [adrianhopebailie/open-payments#7]
From https://github.com/adrianhopebailie/open-payments#creating-agreements

>The URL is also returned in the `name` field of the response.
>This URL (resource name) is the unique identifier for the agreement and is used by the client in any subsequent authorization requests.

This seems to suggest that an invoice would always be referred to by its URL. One example of this not being the case would be if the invoice id were used as the `requestId` for web monetization.

I'm wondering if the `id` should be returned in the invoice response and the URL either removed or renamed from `name`. (Are we including the URL in the response body because of @sharafian 's concern about the accessibility of the `Location` header?)

**Comment by adrianhopebailie** [comment]
This is a common pattern for resource oriented APIs. I took a lot of guidance from Google's docs on this:
See: https://aip.dev/122 and User Specified Ids in https://aip.dev/133

> This seems to suggest that an invoice would always be referred to by its URL. One example of this not being the case would be if the invoice id were used as the requestId for web monetization.

In this case I interpreted this as the `requestId` is mapped to the `invoice_id` in a create operation. i.e. The caller is creating an invoice and requesting that it be given a specific id. Once it is created then it is referenced by its resource name.

> Are we including the URL in the response body because of @sharafian 's concern about the accessibility of the Location header?

Yes. I did some tests and unless you do a redirect (return a 3XX response) the client never has access to the URL in the `Location` header.

**Comment by wilsonianb** [comment]
Thanks for links.
Why not adhere that even more strictly and make the name either `invoices/0f09dc92-84ad-401b-a7c9-441bc6173f4e` or `//wallet.example/invoices/0f09dc92-84ad-401b-a7c9-441bc6173f4e`?

>The caller is creating an invoice and requesting that it be given a specific id. Once it is created then it is referenced by its resource name.

:+1:
