### ISSUE TITLE
Content type on invoice response

### ISSUE THREAD

**Issue by sharafian** [adrianhopebailie/open-payments#9]
This is compatible with current SPSP so I think it should be `application/spsp4+json`. Example shows `application/json` right now

**Comment by adrianhopebailie** [comment]
Our research suggests that using custom content types adds more friction than value.
Everything we've looked at just uses JSON.

The only exception is where APIs use a custom content type for each resource which effectively tells the caller how to do validation on the content (i.e. a content type maps to a schema).

If we are going to use content types I'd suggest we use something like `application/opay-invoice+json` or similar.

**Comment by sharafian** [comment]
right now SPSP expects the application/spsp4+json, otherwise this won't work with existing spsp implementations

**Comment by matdehaast** [comment]
To be backwards compatible we could just make it that if you use `Accept: application/spsp4+json` we respond with that content-type and aim to deprecate it over time

**Comment by adrianhopebailie** [comment]
> right now SPSP expects the application/spsp4+json, otherwise this won't work with existing spsp implementations

Are you saying that server implementations expect this today?

Would `Accept: application/spsp4+json; application/json` work?

Another thought is that we encourage people to use the `POST` method to the appropriate endpoint and that a call directly to the Payment Pointer URL should redirect to the meta-data page UNLESS it contains the `Accept: application/spsp4+json` header which suggests it is using the deprecated behaviour?
